package yougo.entity.po;

public class UserPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.id
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.name
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.phone_no
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.sex
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.age
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.address
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.grade
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.type
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucs_user.id_card_type
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    private String idCardType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.id
     *
     * @return the value of ucs_user.id
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.id
     *
     * @param id the value for ucs_user.id
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.name
     *
     * @return the value of ucs_user.name
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.name
     *
     * @param name the value for ucs_user.name
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.phone_no
     *
     * @return the value of ucs_user.phone_no
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.phone_no
     *
     * @param phoneNo the value for ucs_user.phone_no
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.sex
     *
     * @return the value of ucs_user.sex
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.sex
     *
     * @param sex the value for ucs_user.sex
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.age
     *
     * @return the value of ucs_user.age
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.age
     *
     * @param age the value for ucs_user.age
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.address
     *
     * @return the value of ucs_user.address
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.address
     *
     * @param address the value for ucs_user.address
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.grade
     *
     * @return the value of ucs_user.grade
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.grade
     *
     * @param grade the value for ucs_user.grade
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.type
     *
     * @return the value of ucs_user.type
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.type
     *
     * @param type the value for ucs_user.type
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucs_user.id_card_type
     *
     * @return the value of ucs_user.id_card_type
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public String getIdCardType() {
        return idCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucs_user.id_card_type
     *
     * @param idCardType the value for ucs_user.id_card_type
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    public void setIdCardType(String idCardType) {
        this.idCardType = idCardType == null ? null : idCardType.trim();
    }
}