package yougo.user.dao;

import yougo.entity.po.UserPO;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    int insert(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    int insertSelective(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    UserPO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    int updateByPrimaryKeySelective(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucs_user
     *
     * @mbg.generated Thu May 31 15:18:10 CST 2018
     */
    int updateByPrimaryKey(UserPO record);
}